if (!isServer) exitWith {};
_unit = _this select 0;

removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeGoggles _unit;
_unit forceAddUniform 'rhs_uniform_emr_patchless';
_unit addItemToUniform 'ACE_MapTools';
_unit addItemToUniform 'ACE_EarPlugs';
_unit addItemToUniform 'ACE_Flashlight_XL50';
_unit addVest 'rhs_6b23_digi_sniper';
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_rgd5';};
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_rdg2_white';};
for '_i' from 1 to 10 do {_unit addItem 'rhs_10Rnd_762x54mmR_7N1';};
_unit addWeapon 'rhs_weap_svds';
_unit addPrimaryWeaponItem 'rhs_acc_pso1m2';
_unit addBackpack 'rhs_assault_umbts';
_unit addItemToBackpack 'rhs_weap_vss';
_unit addItemToBackpack 'rhs_mag_nspn_red';
_unit addItemToBackpack 'rhs_mag_nspn_green';
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_mag_rgo';};
for '_i' from 1 to 4 do {_unit addItemToBackpack 'rhs_mine_pmn2_mag';};
_unit addItem "ACE_RangeCard";
_unit addHeadgear 'rhs_beanie_green';
_unit addWeapon "rhs_weap_tr8";
_unit linkItem 'ItemMap';
_unit linkItem 'ItemCompass';
_unit linkItem 'tf_microdagr';
_unit linkItem 'ItemRadio';
_unit linkItem 'ItemGPS';
[_unit] call bn_equip_vdv_rzv1_ace_med;
for '_i' from 1 to 4 do {_unit addItemToBackpack 'rhs_20rnd_9x39mm_SP6';};
_unit addItem 'rhs_acc_pso1m21';
for '_i' from 1 to 4 do {_unit addItem 'rhs_20rnd_9x39mm_SP5';};