if (!isServer) exitWith {};
_unit = _this select 0;

_unit forceAddUniform 'rhs_uniform_flora';
_unit addItemToUniform 'ACE_MapTools';
_unit addItemToUniform 'ACE_EarPlugs';
_unit addItemToUniform 'ACE_Flashlight_XL50';
_unit addItemToUniform 'pzn_vil_1pn34';
_unit addVest 'rhs_6b23_digi_sniper';
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_rgd5';};
for '_i' from 1 to 2 do {_unit addItemToVest 'rhs_mag_rdg2_white';};
for '_i' from 1 to 6 do {_unit addItemToVest 'rhs_10Rnd_762x54mmR_7N1';};
_unit addBackpack 'rhs_assault_umbts';
_unit addItemToBackpack 'rhs_weap_aks74u';
_unit addItemToBackpack 'rhs_mag_nspn_red';
_unit addItemToBackpack 'rhs_mag_nspn_green';
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_mag_rgo';};
for '_i' from 1 to 2 do {_unit addItemToBackpack 'rhs_30Rnd_545x39_7N22_AK';};
_unit addHeadgear 'rhs_6b28';
_unit addWeapon 'rhs_weap_svds';
_unit addPrimaryWeaponItem 'rhs_acc_pso1m2';
_unit addWeapon 'Binocular';
_unit linkItem 'ItemMap';
_unit linkItem 'ItemCompass';
_unit linkItem 'tf_microdagr';
_unit linkItem 'ItemRadio';
[_unit] call bn_equip_ru_msv_ace_med;
