private ["_veh"];
_veh = _this select 0;
clearItemCargoGlobal _veh;
clearMagazineCargoGlobal _veh;
clearWeaponCargoGlobal _veh;
clearBackpackCargoGlobal _veh;
_veh addMagazineCargoGlobal ["rhs_45Rnd_545X39_7N22_AK",2];
_veh addMagazineCargoGlobal ["rhs_45Rnd_545X39_AK_Green",2];
_veh addBackpackCargoGlobal ["rhs_sidor",2];
_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_AK",2];
_veh addMagazineCargoGlobal ["rhs_30Rnd_545x39_AK_green",2];
_veh addMagazineCargoGlobal ["rhs_VOG25",10];
_veh addMagazineCargoGlobal ["rhs_GRD40_Green",3];
_veh addMagazineCargoGlobal ["rhs_VG40OP_white",3];
_veh addItemCargoGlobal ["ACE_Track",1];
_veh addItemCargoGlobal ["ToolKit",1];
_veh addMagazineCargoGlobal ["rhs_100Rnd_762x54mmR",6];
_veh addItemCargoGlobal ["ACE_EntrenchingTool",3];
_veh addItemCargoGlobal ['pzn_f1',12];
_veh addBackpackCargoGlobal ['APOBS_A',1];
_veh addBackpackCargoGlobal ['APOBS_B',1];